-- VHDL Entity ece411.ByteWriter.symbol
--
-- Created:
--          by - hyunyi1.ews (evrt-252-10.ews.illinois.edu)
--          at - 22:12:21 03/27/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ByteWriter IS
   PORT( 
      BH_in   : IN     LC3B_BYTE;
      BL_in   : IN     LC3B_BYTE;
      WH_L    : IN     STD_LOGIC;
      WL_L    : IN     STD_LOGIC;
      WordIn  : IN     LC3B_WORD;
      WordOut : OUT    LC3B_WORD
   );

-- Declarations

END ByteWriter ;

--
-- VHDL Architecture ece411.ByteWriter.struct
--
-- Created:
--          by - hyunyi1.ews (evrt-252-10.ews.illinois.edu)
--          at - 22:12:22 03/27/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY mp3lib;

ARCHITECTURE struct OF ByteWriter IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL F      : lc3b_byte;
   SIGNAL F1     : lc3b_byte;
   SIGNAL H0Word : LC3B_BYTE;
   SIGNAL H1Word : LC3B_BYTE;


   -- Component Declarations
   COMPONENT WordJoiner
   PORT (
      H0Word  : IN     LC3B_BYTE;
      H1Word  : IN     LC3B_BYTE;
      WordOut : OUT    LC3B_WORD
   );
   END COMPONENT;
   COMPONENT WordSplit
   PORT (
      WordIn : IN     LC3B_WORD;
      H0Word : OUT    LC3B_BYTE;
      H1Word : OUT    LC3B_BYTE
   );
   END COMPONENT;
   COMPONENT MUX2_8
   PORT (
      A   : IN     LC3B_BYTE ;
      B   : IN     LC3B_BYTE ;
      SEL : IN     STD_LOGIC ;
      F   : OUT    LC3B_BYTE 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : MUX2_8 USE ENTITY mp3lib.MUX2_8;
   FOR ALL : WordJoiner USE ENTITY ece411.WordJoiner;
   FOR ALL : WordSplit USE ENTITY ece411.WordSplit;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_3 : WordJoiner
      PORT MAP (
         H0Word  => F,
         H1Word  => F1,
         WordOut => WordOut
      );
   U_2 : WordSplit
      PORT MAP (
         H0Word => H0Word,
         H1Word => H1Word,
         WordIn => WordIn
      );
   U_0 : MUX2_8
      PORT MAP (
         A   => BL_in,
         B   => H0Word,
         SEL => WL_L,
         F   => F
      );
   U_1 : MUX2_8
      PORT MAP (
         A   => BH_in,
         B   => H1Word,
         SEL => WH_L,
         F   => F1
      );

END struct;
