-- VHDL Entity ece411.CacheHM.symbol
--
-- Created:
--          by - hyunyi1.ews (evrt-252-10.ews.illinois.edu)
--          at - 22:13:38 03/27/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY CacheHM IS
   PORT( 
      HIT0         : IN     STD_LOGIC;
      HIT1         : IN     STD_LOGIC;
      MREAD_L      : IN     std_logic;
      MWRITEH_L    : IN     std_logic;
      MWRITEL_L    : IN     std_logic;
      V0Flag       : IN     STD_LOGIC;
      V1Flag       : IN     STD_LOGIC;
      CacheHitOut  : OUT    STD_LOGIC;
      CacheMissOut : OUT    STD_LOGIC
   );

-- Declarations

END CacheHM ;

--
-- VHDL Architecture ece411.CacheHM.struct
--
-- Created:
--          by - hyunyi1.ews (evrt-252-10.ews.illinois.edu)
--          at - 22:13:38 03/27/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF CacheHM IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dMREAD_L   : STD_LOGIC;
   SIGNAL dMWRITEH_L : STD_LOGIC;
   SIGNAL dMWRITEL_L : STD_LOGIC;


   -- Component Declarations
   COMPONENT CacheHit
   PORT (
      HIT0      : IN     STD_LOGIC;
      HIT1      : IN     STD_LOGIC;
      MREAD_L   : IN     STD_LOGIC;
      MWRITEH_L : IN     STD_LOGIC;
      MWRITEL_L : IN     STD_LOGIC;
      V0Flag    : IN     STD_LOGIC;
      V1Flag    : IN     STD_LOGIC;
      CacheHit  : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT CacheMiss
   PORT (
      HIT0      : IN     STD_LOGIC;
      HIT1      : IN     STD_LOGIC;
      MREAD_L   : IN     STD_LOGIC;
      MWRITEH_L : IN     STD_LOGIC;
      MWRITEL_L : IN     STD_LOGIC;
      V0Flag    : IN     STD_LOGIC;
      V1Flag    : IN     STD_LOGIC;
      CacheMiss : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT Delayer
   PORT (
      MREAD_L    : IN     std_logic ;
      MWRITEH_L  : IN     std_logic ;
      MWRITEL_L  : IN     std_logic ;
      dMREAD_L   : OUT    STD_LOGIC ;
      dMWRITEH_L : OUT    STD_LOGIC ;
      dMWRITEL_L : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : CacheHit USE ENTITY ece411.CacheHit;
   FOR ALL : CacheMiss USE ENTITY ece411.CacheMiss;
   FOR ALL : Delayer USE ENTITY ece411.Delayer;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : CacheHit
      PORT MAP (
         V0Flag    => V0Flag,
         V1Flag    => V1Flag,
         HIT0      => HIT0,
         HIT1      => HIT1,
         MREAD_L   => dMREAD_L,
         MWRITEH_L => dMWRITEH_L,
         MWRITEL_L => dMWRITEL_L,
         CacheHit  => CacheHitOut
      );
   U_1 : CacheMiss
      PORT MAP (
         V0Flag    => V0Flag,
         V1Flag    => V1Flag,
         HIT0      => HIT0,
         HIT1      => HIT1,
         MREAD_L   => dMREAD_L,
         MWRITEH_L => dMWRITEH_L,
         MWRITEL_L => dMWRITEL_L,
         CacheMiss => CacheMissOut
      );
   aDelayer : Delayer
      PORT MAP (
         MREAD_L    => MREAD_L,
         MWRITEH_L  => MWRITEH_L,
         MWRITEL_L  => MWRITEL_L,
         dMREAD_L   => dMREAD_L,
         dMWRITEH_L => dMWRITEH_L,
         dMWRITEL_L => dMWRITEL_L
      );

END struct;
