-- VHDL Entity ece411.CacheHM.symbol
--
-- Created:
--          by - hyunyi1.ews (gelib-057-09.ews.illinois.edu)
--          at - 21:18:51 03/28/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY CacheHM IS
   PORT( 
      HIT0         : IN     STD_LOGIC;
      HIT1         : IN     STD_LOGIC;
      MREAD_L      : IN     std_logic;
      MWRITEH_L    : IN     std_logic;
      MWRITEL_L    : IN     std_logic;
      V0Flag       : IN     STD_LOGIC;
      V1Flag       : IN     STD_LOGIC;
      CacheHitOut  : OUT    STD_LOGIC;
      CacheMissOut : OUT    STD_LOGIC
   );

-- Declarations

END CacheHM ;

--
-- VHDL Architecture ece411.CacheHM.struct
--
-- Created:
--          by - hyunyi1.ews (gelib-057-09.ews.illinois.edu)
--          at - 21:18:51 03/28/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY mp3lib;

ARCHITECTURE struct OF CacheHM IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL A          : STD_LOGIC;
   SIGNAL A1         : STD_LOGIC;
   SIGNAL F          : STD_LOGIC;
   SIGNAL dMREAD_L   : STD_LOGIC;
   SIGNAL dMWRITEH_L : STD_LOGIC;
   SIGNAL dMWRITEL_L : STD_LOGIC;


   -- Component Declarations
   COMPONENT CacheHit
   PORT (
      HIT0      : IN     STD_LOGIC;
      HIT1      : IN     STD_LOGIC;
      MREAD_L   : IN     STD_LOGIC;
      MWRITEH_L : IN     STD_LOGIC;
      MWRITEL_L : IN     STD_LOGIC;
      V0Flag    : IN     STD_LOGIC;
      V1Flag    : IN     STD_LOGIC;
      CacheHit  : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT CacheMiss
   PORT (
      HIT0      : IN     STD_LOGIC;
      HIT1      : IN     STD_LOGIC;
      MREAD_L   : IN     STD_LOGIC;
      MWRITEH_L : IN     STD_LOGIC;
      MWRITEL_L : IN     STD_LOGIC;
      V0Flag    : IN     STD_LOGIC;
      V1Flag    : IN     STD_LOGIC;
      CacheMiss : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT Delayer
   PORT (
      MREAD_L    : IN     std_logic ;
      MWRITEH_L  : IN     std_logic ;
      MWRITEL_L  : IN     std_logic ;
      dMREAD_L   : OUT    STD_LOGIC ;
      dMWRITEH_L : OUT    STD_LOGIC ;
      dMWRITEL_L : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT AND2
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT NAND3
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      C : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AND2 USE ENTITY mp3lib.AND2;
   FOR ALL : CacheHit USE ENTITY ece411.CacheHit;
   FOR ALL : CacheMiss USE ENTITY ece411.CacheMiss;
   FOR ALL : Delayer USE ENTITY ece411.Delayer;
   FOR ALL : NAND3 USE ENTITY mp3lib.NAND3;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : CacheHit
      PORT MAP (
         V0Flag    => V0Flag,
         V1Flag    => V1Flag,
         HIT0      => HIT0,
         HIT1      => HIT1,
         MREAD_L   => dMREAD_L,
         MWRITEH_L => dMWRITEH_L,
         MWRITEL_L => dMWRITEL_L,
         CacheHit  => A
      );
   U_1 : CacheMiss
      PORT MAP (
         V0Flag    => V0Flag,
         V1Flag    => V1Flag,
         HIT0      => HIT0,
         HIT1      => HIT1,
         MREAD_L   => dMREAD_L,
         MWRITEH_L => dMWRITEH_L,
         MWRITEL_L => dMWRITEL_L,
         CacheMiss => A1
      );
   aDelayer : Delayer
      PORT MAP (
         MREAD_L    => MREAD_L,
         MWRITEH_L  => MWRITEH_L,
         MWRITEL_L  => MWRITEL_L,
         dMREAD_L   => dMREAD_L,
         dMWRITEH_L => dMWRITEH_L,
         dMWRITEL_L => dMWRITEL_L
      );
   U_3 : AND2
      PORT MAP (
         A => A,
         B => F,
         F => CacheHitOut
      );
   U_4 : AND2
      PORT MAP (
         A => A1,
         B => F,
         F => CacheMissOut
      );
   U_2 : NAND3
      PORT MAP (
         A => MREAD_L,
         B => MWRITEH_L,
         C => MWRITEL_L,
         F => F
      );

END struct;
