-- VHDL Entity ece411.CacheHML1I.symbol
--
-- Created:
--          by - hyunyi1.ews (gelib-057-09.ews.illinois.edu)
--          at - 21:08:10 03/28/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY CacheHML1I IS
   PORT( 
      HIT       : IN     STD_LOGIC;
      MREAD_L   : IN     std_logic;
      VFlag     : IN     STD_LOGIC;
      CacheHit  : OUT    STD_LOGIC;
      CacheMiss : OUT    STD_LOGIC
   );

-- Declarations

END CacheHML1I ;

--
-- VHDL Architecture ece411.CacheHML1I.struct
--
-- Created:
--          by - hyunyi1.ews (gelib-057-09.ews.illinois.edu)
--          at - 21:08:11 03/28/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY mp3lib;

ARCHITECTURE struct OF CacheHML1I IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL B        : STD_LOGIC;
   SIGNAL F        : STD_LOGIC;
   SIGNAL dMREAD_L : STD_LOGIC;


   -- Component Declarations
   COMPONENT CacheHitL1I
   PORT (
      HIT      : IN     STD_LOGIC;
      MREAD_L  : IN     STD_LOGIC;
      VFlag    : IN     STD_LOGIC;
      CacheHit : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT CacheMissL1I
   PORT (
      HIT       : IN     STD_LOGIC;
      MREAD_L   : IN     STD_LOGIC;
      VFlag     : IN     STD_LOGIC;
      CacheMiss : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT DelayCHML1I
   PORT (
      MREAD_L  : IN     std_logic ;
      dMREAD_L : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT AND2
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT NOT1
   PORT (
      A : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AND2 USE ENTITY mp3lib.AND2;
   FOR ALL : CacheHitL1I USE ENTITY ece411.CacheHitL1I;
   FOR ALL : CacheMissL1I USE ENTITY ece411.CacheMissL1I;
   FOR ALL : DelayCHML1I USE ENTITY ece411.DelayCHML1I;
   FOR ALL : NOT1 USE ENTITY mp3lib.NOT1;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : CacheHitL1I
      PORT MAP (
         VFlag    => VFlag,
         HIT      => HIT,
         MREAD_L  => dMREAD_L,
         CacheHit => B
      );
   U_1 : CacheMissL1I
      PORT MAP (
         VFlag     => VFlag,
         HIT       => HIT,
         MREAD_L   => dMREAD_L,
         CacheMiss => CacheMiss
      );
   aDelay : DelayCHML1I
      PORT MAP (
         MREAD_L  => MREAD_L,
         dMREAD_L => dMREAD_L
      );
   U_3 : AND2
      PORT MAP (
         A => F,
         B => B,
         F => CacheHit
      );
   U_2 : NOT1
      PORT MAP (
         A => MREAD_L,
         F => F
      );

END struct;
