-- VHDL Entity ece411.EXECUTE_MEM_LATCH.interface
--
-- Created:
--          by - mccart18.ews (gelib-057-05.ews.illinois.edu)
--          at - 07:44:18 03/13/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY EXECUTE_MEM_LATCH IS
   PORT( 
      ALU_OUT                  : IN     LC3B_WORD;
      CLK                      : IN     std_logic;
      DR_EXECUTE_OUT           : IN     STD_LOGIC_VECTOR (2 DOWNTO 0);
      EXECUTE_CONTROL_WORD_OUT : IN     lc3b_word;
      EXEC_ADDR                : IN     LC3B_WORD;
      RESET_L                  : IN     STD_LOGIC;
      STALL_L                  : IN     std_logic;
      DR_MEM_IN                : OUT    STD_LOGIC_VECTOR (2 DOWNTO 0);
      EXEC_ADDR_MEM            : OUT    STD_LOGIC_VECTOR (15 DOWNTO 0);
      MEM_ALU_IN               : OUT    STD_LOGIC_VECTOR (15 DOWNTO 0);
      MEM_CONTROL_WORD_IN      : OUT    STD_LOGIC_VECTOR (15 DOWNTO 0)
   );

-- Declarations

END EXECUTE_MEM_LATCH ;

--
-- VHDL Architecture ece411.EXECUTE_MEM_LATCH.struct
--
-- Created:
--          by - mccart18.ews (gelib-057-05.ews.illinois.edu)
--          at - 07:44:18 03/13/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF EXECUTE_MEM_LATCH IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL CLK1     : std_logic;
   SIGNAL CLK2     : std_logic;
   SIGNAL CLK3     : std_logic;
   SIGNAL RESET_L1 : STD_LOGIC;
   SIGNAL RESET_L2 : STD_LOGIC;
   SIGNAL RESET_L3 : STD_LOGIC;
   SIGNAL STALL_L1 : std_logic;
   SIGNAL STALL_L2 : std_logic;
   SIGNAL STALL_L3 : std_logic;


   -- Component Declarations
   COMPONENT REG16
   PORT (
      A       : IN     STD_LOGIC_VECTOR (15 DOWNTO 0);
      CLK     : IN     STD_LOGIC;
      EN      : IN     STD_LOGIC;
      RESET_L : IN     STD_LOGIC;
      F       : OUT    STD_LOGIC_VECTOR (15 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT REG3
   PORT (
      A       : IN     STD_LOGIC_VECTOR (2 DOWNTO 0);
      CLK     : IN     STD_LOGIC;
      EN      : IN     STD_LOGIC;
      RESET_L : IN     STD_LOGIC;
      F       : OUT    STD_LOGIC_VECTOR (2 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : REG16 USE ENTITY ece411.REG16;
   FOR ALL : REG3 USE ENTITY ece411.REG3;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_4 : REG16
      PORT MAP (
         RESET_L => RESET_L1,
         A       => EXECUTE_CONTROL_WORD_OUT,
         EN      => STALL_L1,
         CLK     => CLK1,
         F       => MEM_CONTROL_WORD_IN
      );
   U_5 : REG16
      PORT MAP (
         RESET_L => RESET_L2,
         A       => EXEC_ADDR,
         EN      => STALL_L2,
         CLK     => CLK2,
         F       => EXEC_ADDR_MEM
      );
   U_6 : REG16
      PORT MAP (
         RESET_L => RESET_L3,
         A       => ALU_OUT,
         EN      => STALL_L3,
         CLK     => CLK3,
         F       => MEM_ALU_IN
      );
   U_7 : REG3
      PORT MAP (
         RESET_L => RESET_L,
         A       => DR_EXECUTE_OUT,
         EN      => STALL_L,
         CLK     => CLK,
         F       => DR_MEM_IN
      );

END struct;
