-- VHDL Entity ece411.IMREAD_Calc.symbol
--
-- Created:
--          by - hyunyi1.ews (gelib-057-39.ews.illinois.edu)
--          at - 21:37:42 03/13/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY IMREAD_Calc IS
   PORT( 
      CLK     : IN     STD_LOGIC;
      MRESP_H : IN     std_logic;
      RESET_L : IN     STD_LOGIC;
      STALL_L : IN     STD_LOGIC;
      MREAD_L : OUT    STD_LOGIC
   );

-- Declarations

END IMREAD_Calc ;

--
-- VHDL Architecture ece411.IMREAD_Calc.struct
--
-- Created:
--          by - hyunyi1.ews (gelib-057-39.ews.illinois.edu)
--          at - 21:37:42 03/13/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF IMREAD_Calc IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL IMReset : STD_LOGIC;

   -- Implicit buffer signal declarations
   SIGNAL MREAD_L_internal : STD_LOGIC;


   -- Component Declarations
   COMPONENT IMread_Reset
   PORT (
      MREAD_L : IN     STD_LOGIC ;
      MRESP_H : IN     std_logic ;
      STALL_L : IN     STD_LOGIC ;
      IMReset : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT REG1_INVERT
   PORT (
      CLK     : IN     STD_LOGIC;
      EN      : IN     STD_LOGIC;
      RESET_L : IN     STD_LOGIC;
      SET_L   : IN     STD_LOGIC;
      F       : OUT    STD_LOGIC
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : IMread_Reset USE ENTITY ece411.IMread_Reset;
   FOR ALL : REG1_INVERT USE ENTITY ece411.REG1_INVERT;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_2 : IMread_Reset
      PORT MAP (
         MREAD_L => MREAD_L_internal,
         MRESP_H => MRESP_H,
         STALL_L => STALL_L,
         IMReset => IMReset
      );
   U_0 : REG1_INVERT
      PORT MAP (
         RESET_L => RESET_L,
         SET_L   => IMReset,
         EN      => STALL_L,
         CLK     => CLK,
         F       => MREAD_L_internal
      );

   -- Implicit buffered output assignments
   MREAD_L <= MREAD_L_internal;

END struct;
