-- VHDL Entity ece411.mp3_cpu.symbol
--
-- Created:
--          by - hyunyi1.ews (gelib-057-39.ews.illinois.edu)
--          at - 23:58:35 03/13/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY mp3_cpu IS
   PORT( 
      RESET_L : IN     STD_LOGIC
   );

-- Declarations

END mp3_cpu ;

--
-- VHDL Architecture ece411.mp3_cpu.struct
--
-- Created:
--          by - hyunyi1.ews (gelib-057-39.ews.illinois.edu)
--          at - 23:58:35 03/13/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF mp3_cpu IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL CLK         : std_logic;
   SIGNAL D_MADDR     : LC3B_WORD;
   SIGNAL D_MDATAIN   : LC3B_WORD;
   SIGNAL D_MDATAOUT  : lc3b_word;
   SIGNAL D_MREAD_L   : std_logic;
   SIGNAL D_MRESP_H   : STD_LOGIC;
   SIGNAL D_MWRITEH_L : std_logic;
   SIGNAL D_MWRITEL_L : std_logic;
   SIGNAL I_ADDR      : lc3b_word;
   SIGNAL I_DATAIN    : LC3B_WORD;
   SIGNAL I_MREAD_L   : std_logic;
   SIGNAL I_MRESP_H   : STD_LOGIC;
   SIGNAL STALL_L     : std_logic;


   -- Component Declarations
   COMPONENT BUF1
   PORT (
      BITin  : IN     STD_LOGIC;
      BITout : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT CLKgen
   PORT (
      clk : INOUT  std_logic  := '0'
   );
   END COMPONENT;
   COMPONENT DATAPATH
   PORT (
      CLK         : IN     std_logic ;
      D_MDATAIN   : IN     LC3B_WORD ;
      D_MRESP_H   : IN     STD_LOGIC ;
      I_DATAIN    : IN     LC3B_WORD ;
      I_MRESP_H   : IN     STD_LOGIC ;
      RESET_L     : IN     STD_LOGIC ;
      STALL_L     : IN     std_logic ;
      D_MADDR     : OUT    LC3B_WORD ;
      D_MDATAOUT  : OUT    lc3b_word ;
      D_MREAD_L   : OUT    std_logic ;
      D_MWRITEH_L : OUT    std_logic ;
      D_MWRITEL_L : OUT    std_logic ;
      I_ADDR      : OUT    LC3B_WORD ;
      I_MREAD_L   : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT MagicMemory
   PORT (
      CLK         : IN     STD_LOGIC;
      D_ADDRESS   : IN     LC3B_WORD;
      D_DATAOUT   : IN     LC3B_WORD;
      D_MREAD_L   : IN     STD_LOGIC;
      D_MWRITEH_L : IN     STD_LOGIC;
      D_MWRITEL_L : IN     STD_LOGIC;
      I_ADDRESS   : IN     LC3B_WORD;
      I_MREAD_L   : IN     STD_LOGIC;
      RESET_L     : IN     STD_LOGIC;
      D_DATAIN    : OUT    LC3B_WORD;
      D_MRESP_H   : OUT    STD_LOGIC;
      I_DATAIN    : OUT    LC3B_WORD;
      I_MRESP_H   : OUT    STD_LOGIC
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : BUF1 USE ENTITY ece411.BUF1;
   FOR ALL : CLKgen USE ENTITY ece411.CLKgen;
   FOR ALL : DATAPATH USE ENTITY ece411.DATAPATH;
   FOR ALL : MagicMemory USE ENTITY ece411.MagicMemory;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : BUF1
      PORT MAP (
         BITin  => RESET_L,
         BITout => STALL_L
      );
   aCLK : CLKgen
      PORT MAP (
         clk => CLK
      );
   aDATAPATH : DATAPATH
      PORT MAP (
         CLK         => CLK,
         D_MDATAIN   => D_MDATAIN,
         D_MRESP_H   => D_MRESP_H,
         I_DATAIN    => I_DATAIN,
         I_MRESP_H   => I_MRESP_H,
         RESET_L     => RESET_L,
         STALL_L     => STALL_L,
         D_MADDR     => D_MADDR,
         D_MDATAOUT  => D_MDATAOUT,
         D_MREAD_L   => D_MREAD_L,
         D_MWRITEH_L => D_MWRITEH_L,
         D_MWRITEL_L => D_MWRITEL_L,
         I_ADDR      => I_ADDR,
         I_MREAD_L   => I_MREAD_L
      );
   aMagicMem : MagicMemory
      PORT MAP (
         RESET_L     => RESET_L,
         CLK         => CLK,
         I_MREAD_L   => I_MREAD_L,
         I_ADDRESS   => I_ADDR,
         I_MRESP_H   => I_MRESP_H,
         I_DATAIN    => I_DATAIN,
         D_MREAD_L   => D_MREAD_L,
         D_MWRITEH_L => D_MWRITEH_L,
         D_MWRITEL_L => D_MWRITEL_L,
         D_ADDRESS   => D_MADDR,
         D_DATAOUT   => D_MDATAOUT,
         D_DATAIN    => D_MDATAIN,
         D_MRESP_H   => D_MRESP_H
      );

END struct;
