-- VHDL Entity ece411.NZP_Calc.symbol
--
-- Created:
--          by - hyunyi1.ews (evrt-252-04.ews.illinois.edu)
--          at - 13:24:58 03/14/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY NZP_Calc IS
   PORT( 
      BR      : IN     STD_LOGIC;
      CCin    : IN     lc3b_cc;
      CLK     : IN     std_logic;
      NZPin   : IN     std_logic_vector (2 DOWNTO 0);
      RESET_L : IN     STD_LOGIC;
      STALL_L : IN     STD_LOGIC;
      BRsel   : OUT    STD_LOGIC
   );

-- Declarations

END NZP_Calc ;

--
-- VHDL Architecture ece411.NZP_Calc.struct
--
-- Created:
--          by - hyunyi1.ews (evrt-252-04.ews.illinois.edu)
--          at - 13:24:58 03/14/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF NZP_Calc IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL F      : STD_LOGIC;
   SIGNAL Result : std_logic;


   -- Component Declarations
   COMPONENT AND2
   PORT (
      A : IN     STD_LOGIC;
      B : IN     STD_LOGIC;
      F : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT NZPhit
   PORT (
      CCin   : IN     lc3b_cc ;
      NZPin  : IN     std_logic_vector (2 DOWNTO 0);
      Result : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT REG1
   PORT (
      A       : IN     STD_LOGIC;
      CLK     : IN     STD_LOGIC;
      EN      : IN     STD_LOGIC;
      RESET_L : IN     STD_LOGIC;
      F       : OUT    STD_LOGIC
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AND2 USE ENTITY ece411.AND2;
   FOR ALL : NZPhit USE ENTITY ece411.NZPhit;
   FOR ALL : REG1 USE ENTITY ece411.REG1;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_2 : AND2
      PORT MAP (
         A => Result,
         B => BR,
         F => F
      );
   U_0 : NZPhit
      PORT MAP (
         CCin   => CCin,
         NZPin  => NZPin,
         Result => Result
      );
   U_1 : REG1
      PORT MAP (
         RESET_L => RESET_L,
         A       => F,
         EN      => STALL_L,
         CLK     => CLK,
         F       => BRsel
      );

END struct;
