-- VHDL Entity ece411.Offset_Sel_L1.symbol
--
-- Created:
--          by - hyunyi1.ews (gelib-057-09.ews.illinois.edu)
--          at - 22:31:20 03/28/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Offset_Sel_L1 IS
   PORT( 
      OFFSET  : IN     lc3b_c_offset;
      OWordIn : IN     lc3b_oword;
      WordOut : OUT    LC3B_WORD
   );

-- Declarations

END Offset_Sel_L1 ;

--
-- VHDL Architecture ece411.Offset_Sel_L1.struct
--
-- Created:
--          by - hyunyi1.ews (gelib-057-09.ews.illinois.edu)
--          at - 22:31:20 03/28/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF Offset_Sel_L1 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL A   : LC3B_WORD;
   SIGNAL B   : LC3B_WORD;
   SIGNAL C   : LC3B_WORD;
   SIGNAL D   : LC3B_WORD;
   SIGNAL E   : LC3B_WORD;
   SIGNAL F   : LC3B_WORD;
   SIGNAL G   : LC3B_WORD;
   SIGNAL H   : LC3B_WORD;
   SIGNAL SEL : STD_LOGIC_VECTOR(2 DOWNTO 0);


   -- Component Declarations
   COMPONENT MUX8_16
   PORT (
      A   : IN     LC3B_WORD;
      B   : IN     LC3B_WORD;
      C   : IN     LC3B_WORD;
      D   : IN     LC3B_WORD;
      E   : IN     LC3B_WORD;
      F   : IN     LC3B_WORD;
      G   : IN     LC3B_WORD;
      H   : IN     LC3B_WORD;
      SEL : IN     STD_LOGIC_VECTOR (2 DOWNTO 0);
      I   : OUT    LC3B_WORD
   );
   END COMPONENT;
   COMPONENT OWordSplit
   PORT (
      OWordIn : IN     lc3b_oword;
      A       : OUT    LC3B_WORD;
      B       : OUT    LC3B_WORD;
      C       : OUT    LC3B_WORD;
      D       : OUT    LC3B_WORD;
      E       : OUT    LC3B_WORD;
      F       : OUT    LC3B_WORD;
      G       : OUT    LC3B_WORD;
      H       : OUT    LC3B_WORD
   );
   END COMPONENT;
   COMPONENT OffsetOffset
   PORT (
      OFFSET : IN     lc3b_c_offset;
      SEL    : OUT    STD_LOGIC_VECTOR (2 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : MUX8_16 USE ENTITY ece411.MUX8_16;
   FOR ALL : OWordSplit USE ENTITY ece411.OWordSplit;
   FOR ALL : OffsetOffset USE ENTITY ece411.OffsetOffset;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : MUX8_16
      PORT MAP (
         A   => A,
         B   => B,
         C   => C,
         D   => D,
         E   => E,
         F   => F,
         G   => G,
         H   => H,
         SEL => SEL,
         I   => WordOut
      );
   U_0 : OWordSplit
      PORT MAP (
         OWordIn => OWordIn,
         A       => A,
         B       => B,
         C       => C,
         D       => D,
         E       => E,
         F       => F,
         G       => G,
         H       => H
      );
   U_2 : OffsetOffset
      PORT MAP (
         OFFSET => OFFSET,
         SEL    => SEL
      );

END struct;
