-- VHDL Entity ece411.WRITEBACK.generatedInstance
--
-- Created:
--          by - mccart18.ews (gelib-057-05.ews.illinois.edu)
--          at - 07:58:05 03/13/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY WRITEBACK IS
   PORT( 
      CLK                : IN     std_logic;
      DR                 : OUT    lc3b_word;
      DR_WB_IN           : IN     lc3b_REG;
      LD_REG             : OUT    STD_LOGIC;
      RESET_L            : IN     STD_LOGIC;
      STALL_L            : IN     std_logic;
      WB_ALU_IN          : IN     LC3B_WORD;
      WB_CONTROL_WORD_IN : IN     LC3B_WORD;
      WB_MDR_IN          : IN     LC3B_WORD;
      WDATA              : OUT    LC3B_WORD
   );

END WRITEBACK ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF WRITEBACK IS 
BEGIN


END generatedInstance;
