-- VHDL Entity ece411.ADJ11.generatedInstance
--
-- Created:
--          by - mccart18.ews (gelib-057-33.ews.illinois.edu)
--          at - 04:44:37 02/19/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ADJ11 IS
   PORT( 
      ADJ11out : OUT    LC3b_word;
      clk      : IN     std_logic;
      offset11 : IN     LC3b_offset11
   );

END ADJ11 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF ADJ11 IS 
BEGIN


END generatedInstance;
