-- VHDL Entity ece411.EightGen.generatedInstance
--
-- Created:
--          by - mccart18.ews (evrt-252-13.ews.illinois.edu)
--          at - 17:50:39 02/20/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY EightGen IS
   PORT( 
      clk      : IN     std_logic;
      EightSig : OUT    LC3b_word
   );

END EightGen ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF EightGen IS 
BEGIN


END generatedInstance;
