-- VHDL Entity ece411.ZeroGen.generatedInstance
--
-- Created:
--          by - mccart18.ews (gelib-057-33.ews.illinois.edu)
--          at - 04:52:56 02/19/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ZeroGen IS
   PORT( 
      clk     : IN     std_logic;
      ZeroSig : OUT    LC3b_word
   );

END ZeroGen ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF ZeroGen IS 
BEGIN


END generatedInstance;
