echo "--- Executing initialization force file for ../testcode/mp1code.asm ---"

echo "Resetting processor for 5 ns."
force /reset_l 0 @0
force /reset_l 1 @5
force /stall_l 1 @0
echo "Initializing the processor."
--force /start_h 0 @0
--force /start_h 1 @10

-- Test case: lowering start_h should not impact the function of the processor
--force /start_h 0 @ 100

echo "Done initializing processor, loading ../testcode/mp1code.asm program code."
run 5
change /mp3_cpu/aMagicMem/vhdl_memory/mem(0) X"00"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(1) X"00"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(2) X"17"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(3) X"62"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(4) X"00"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(5) X"14"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(6) X"18"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(7) X"66"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(8) X"01"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(9) X"18"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(10) X"81"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(11) X"14"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(12) X"BF"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(13) X"9A"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(14) X"41"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(15) X"1B"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(16) X"C5"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(17) X"1A"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(18) X"0A"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(19) X"08"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(20) X"00"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(21) X"1E"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(22) X"40"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(23) X"1C"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(24) X"C4"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(25) X"1F"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(26) X"81"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(27) X"1D"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(28) X"BF"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(29) X"9B"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(30) X"41"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(31) X"1B"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(32) X"85"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(33) X"1A"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(34) X"FA"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(35) X"07"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(36) X"07"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(37) X"18"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(38) X"F1"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(39) X"0F"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(40) X"19"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(41) X"78"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(42) X"1A"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(43) X"62"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(44) X"FF"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(45) X"0F"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(46) X"01"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(47) X"00"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(48) X"05"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(49) X"00"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(50) X"00"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(51) X"00"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(52) X"0D"
change /mp3_cpu/aMagicMem/vhdl_memory/mem(53) X"60"
run 5
echo "Done loading ../testcode/mp1code.asm program code."
