onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /mp2_cpu/RESET_L
add wave -noupdate /mp2_cpu/START_H
add wave -noupdate /mp2_cpu/clk
add wave -noupdate /mp2_cpu/theDatapath/PCout
add wave -noupdate /mp2_cpu/theDatapath/ADDRESS
add wave -noupdate /mp2_cpu/MWRITEL_L
add wave -noupdate /mp2_cpu/MWRITEH_L
add wave -noupdate /mp2_cpu/MREAD_L
add wave -noupdate /mp2_cpu/DRAM/MISS
add wave -noupdate /mp2_cpu/DRAM/MREAD_L
add wave -noupdate /mp2_cpu/DRAM/MRESP_H
add wave -noupdate /mp2_cpu/DRAM/MRESP_H_internal
add wave -noupdate /mp2_cpu/DRAM/MWRITEH_L
add wave -noupdate /mp2_cpu/DRAM/MWRITEL_L
add wave -noupdate /mp2_cpu/DRAM/PMADDRESS
add wave -noupdate /mp2_cpu/DRAM/PMDATAIN
add wave -noupdate /mp2_cpu/DRAM/PMDATAOUT
add wave -noupdate /mp2_cpu/DRAM/PMREAD_L
add wave -noupdate /mp2_cpu/DRAM/PMRESP_H
add wave -noupdate /mp2_cpu/DRAM/PMWRITE_L
add wave -noupdate /mp2_cpu/DRAM/in_idle_hit
add wave -noupdate /mp2_cpu/DRAM/in_load
add wave -noupdate /mp2_cpu/DRAM/in_wbc
add wave -noupdate /mp2_cpu/DATAIN
add wave -noupdate /mp2_cpu/DATAOUT
add wave -noupdate -expand /mp2_cpu/theDatapath/aRegFile/RAM
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/ADDRESS
add wave -noupdate /mp2_cpu/theDatapath/MDROUT
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/DATAOUT
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/MREAD_L
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/MWRITEH_L
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/MWRITEL_L
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/PMDATAIN
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/RESET_L
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/clk
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/in_idle_hit
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/in_load
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/in_wbc
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/DATAIN
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/MISS
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/MRESP_H
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/PMADDRESS
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/PMDATAOUT
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/C_ACCESS
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/EvictTag
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/INDEX
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/LRUout
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/LRUout_NOT
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/OFFSET
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/Prehit0
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/Prehit1
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/Protohit
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/Protohit_NOT
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/TAG
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/TagOut
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/TagOut1
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/WBADDR
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/Way0Write
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/Way1Write
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/WayData0
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/WayData1
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/WayData_Word0
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/WayData_Word1
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/clk_NOT
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/clk_delayed
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/hit_gate
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/MRESP_H_internal
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/Way0/DataArray/Data
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/Way0/TagArray/Data
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/Way0/ValidArray/Data
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/Way1/DataArray/Data
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/Way1/TagArray/Data
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/Way1/ValidArray/Data
add wave -noupdate /mp2_cpu/DRAM/Cache_DP/LRU/Data
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {4457 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 450
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {2293 ns} {4572 ns}
